package com.tsinghua.demo;

public class Example {

	/*JSONObject obj = JSONObject.fromObject(log[i]);
	String screenResolutionLong = obj.getString("screenResolutionLong");
	String screenResolutionWidth = obj.getString("screenResolutionWidth");
	String videoClarity = obj.getString("videoClarity");
	String videoCodingFormat = obj.getString("videoCodingFormat");
	String videoBitrate = obj.getString("videoBitrate");
	String bufferingDelay = obj.getString("bufferingDelay");
	String videoPeakRate = obj.getString("videoPeakRate");
	String videoKaNum = obj.getString("videoKaNum");
	String videoKaTotalTime = obj.getString("videoKaTotalTime");
	String kaDurationProportion = obj.getString("kaDurationProportion");
	String kaDurationLongOne = obj.getString("kaDurationLongOne");
	String kaDurationLongPointOne = obj.getString("kaDurationLongPointOne");
	String kaDurationLongTwo = obj.getString("kaDurationLongTwo");
	String kaDurationLongPointTwo = obj.getString("kaDurationLongPointTwo");
	String kaDurationLongThree = obj.getString("kaDurationLongThree");
	String kaDurationLongPointThree = obj.getString("kaDurationLongPointThree");
	String kaDurationLongFour = obj.getString("kaDurationLongFour");
	String kaDurationLongPointFour = obj.getString("kaDurationLongPointFour");
	String kaDurationLongFive = obj.getString("kaDurationLongFive");
	String kaDurationLongPointFive = obj.getString("kaDurationLongPointFive");
	String kaDurationLongSix = obj.getString("kaDurationLongSix");
	String kaDurationLongPointSix = obj.getString("kaDurationLongPointSix");
	String kaDurationLongSeven = obj.getString("kaDurationLongSeven");
	String kaDurationLongPointSeven = obj.getString("kaDurationLongPointSeven");
	String kaDurationLongEight = obj.getString("kaDurationLongEight");
	String kaDurationLongPointEight = obj.getString("kaDurationLongPointEight");
	String kaDurationLongNine = obj.getString("kaDurationLongNine");
	String kaDurationLongPointNine = obj.getString("kaDurationLongPointNine");
	String kaDurationLongTen = obj.getString("kaDurationLongTen");
	String kaDurationLongPointTen = obj.getString("kaDurationLongPointTen");
	String videoTotalTime = obj.getString("videoTotalTime");
	String videoPlayTotalTime = obj.getString("videoPlayTotalTime");
	String videoAllPeakRate = obj.getString("videoAllPeakRate");
	String videoAveragePeakRate = obj.getString("videoAveragePeakRate");
	String lightIntensity = obj.getString("lightIntensity");
	String phoneScreenBrightness = obj.getString("phoneScreenBrightness");
	String phonePlaceState = obj.getString("phonePlaceState");
	String environmentalNoise = obj.getString("environmentalNoise");
	String networkType = obj.getString("networkType");
	String phoneElectricStart = obj.getString("phoneElectricStart");
	String phoneElectricEnd = obj.getString("phoneElectricEnd");
	String signalStrength = obj.getString("signalStrength");
	String phoneVersion = obj.getString("phoneVersion");
	String operatingSystem = obj.getString("operatingSystem");
	String gpsLongitudeOne = obj.getString("gpsLongitudeOne");
	String gpsLatitudeOne = obj.getString("gpsLatitudeOne");
	String gpsLongitudeTwo = obj.getString("gpsLongitudeTwo");
	String gpsLatitudeTwo = obj.getString("gpsLatitudeTwo");
	String gpsLongitudeThree = obj.getString("gpsLongitudeThree");
	String gpsLatitudeThree = obj.getString("gpsLatitudeThree");
	String gpsLongitudeFour = obj.getString("gpsLongitudeFour");
	String gpsLatitudeFour = obj.getString("gpsLatitudeFour");
	String gpsLongitudeFive = obj.getString("gpsLongitudeFive");
	String gpsLatitudeFive = obj.getString("gpsLatitudeFive");
	String accelerometerData = obj.getString("accelerometerData");
	String instanDownloadSpeed = obj.getString("instanDownloadSpeed");
	String Equality = obj.getString("Equality"); // 用户对视频清晰度的评分
	String Eloading = obj.getString("Eloading"); // 用户对视频播放等待时间的评分
	String Estalling = obj.getString("Estalling"); // 用户对流畅度的评分
	String EvMos = obj.getString("EvMos"); // 用户对整体视频服务的综合评分
	String PhoneNum = obj.getString("PhoneNum"); // 电话号
	String Cid = obj.getString("Cid"); // 小区标识
	String Lac = obj.getString("Lac"); // 位置区编码
	String userScene = obj.getString("userScene"); // 用户场景
	// 二期优化字段
	String VideoServerIP = obj.getString("VideoServerIP"); // 视频源IP地址
	String VideoServerLocation = obj.getString("VideoServerLocation"); // 视频服务器位置
	String Country = obj.getString("Country"); // 国家/地区
	String Province = obj.getString("Province"); // 省份
	String City = obj.getString("City"); // 城市
	String Address = obj.getString("Address"); // 地址
	String UEInternalIP = obj.getString("UEInternalIP"); // 手机IP
	String Elight = obj.getString("Elight"); // 环境光照对视频观看的影响程度
	String Estate = obj.getString("Estate"); // 用户对运动状态的反馈
	String PLMN = obj.getString("PLMN"); // 公共陆地移动网络
	String IMSI = obj.getString("IMSI"); // 国际移动用户识别码
	String UDID = obj.getString("UDID"); // 移动设备国际身份码
	String MCC = obj.getString("MCC"); // 移动国家码
	String MNC = obj.getString("MNC"); // 移动网络号码
	String CellSignalStrength = obj.getString("CellSignalStrength"); // 无线蜂窝网络场强(dBm)
	String SINR = obj.getString("SINR"); // 信号干扰噪声比
	String PingAvgRTT = obj.getString("PingAvgRTT"); // 视频服务器RTT
	String Carrier = obj.getString("Carrier"); // SIM运营商
	String ENodeBID = obj.getString("ENodeBID"); // 基站标识
	String PlayWay = obj.getString("PlayWay"); // 直播or点播
	Date date = new Date();// 入库时间
	// 后加字段
	String videoStartTime = obj.getString("videoStartTime"); // 视频开始时间
	String videoSize = obj.getString("videoSize"); // 视频大小
	String videoName = obj.getString("videoName");// 视频名称
	String userBufferTime = obj.getString("userBufferTime");// 缓冲时间
	DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
	Date startTime = fmt.parse(videoStartTime);*/
}
